### ISSUE TITLE
NoSQLMap is unable to find target

### ISSUE THREAD

**Issue by g0tmi1k** [codingo/NoSQLMap#30] opened 2016-01-11 15:18 UTC
Using commit 898a60b0c916eb53ec65b7417baffddaf74f41b5.

NoSQLMap is reporting the target does not response correctly, when in fact it is (See cURL at the end).

**Edit**:
Another issue - when it cannot find the target, re-running will cause a crash. (see first comment)

```
root@kali:~/NoSQLMap-0.5# cat test 
xx.xx.xx.xxx,443,/cgi-bin/mongo/2.2.3/dbparse.py,GET,Not Set,Not Set,ON,ON,
{}root@kali:~/NoSQLMap-0.5# python nosqlmap.py 
[3;J
====================================================
 _   _       _____  _____ _     ___  ___            
| \ | |     /  ___||  _  | |    |  \/  |            
|  \| | ___ \ `--. | | | | |    | .  . | __ _ _ __  
| . ` |/ _ \ `--. \| | | | |    | |\/| |/ _` | '_ \ 
| |\  | (_) /\__/ /\ \/' / |____| |  | | (_| | |_) |
\_| \_/\___/\____/  \_/\_\_____/\_|  |_/\__,_| .__/
====================================================
NoSQLMap-v0.5
nosqlmap@gmail.com


1-Set options
2-NoSQL DB Access Attacks
3-NoSQL Web App attacks
4-Scan for Anonymous MongoDB Access
5-Change Platform (Current: MongoDB)
x-Exit
Select an option: 1



Options
1-Set target host/IP (Current: Not Set)
2-Set web app port (Current: 80)
3-Set App Path (Current: Not Set)
4-Toggle HTTPS (Current: OFF)
5-Set MongoDB Port (Current : 27017)
6-Set HTTP Request Method (GET/POST) (Current: GET)
7-Set my local MongoDB/Shell IP (Current: Not Set)
8-Set shell listener port (Current: Not Set)
9-Toggle Verbose Mode: (Current: OFF)
0-Load options file
a-Load options from saved Burp request
b-Save options file
x-Back to main menu
Select an option: 0
Enter file name to load: test



Options
1-Set target host/IP (Current: xx.xx.xx.xxx)
2-Set web app port (Current: 443)
3-Set App Path (Current: /cgi-bin/mongo/2.2.3/dbparse.py)
4-Toggle HTTPS (Current: ON)
5-Set MongoDB Port (Current : 27017)
6-Set HTTP Request Method (GET/POST) (Current: GET)
7-Set my local MongoDB/Shell IP (Current: Not Set)
8-Set shell listener port (Current: Not Set)
9-Toggle Verbose Mode: (Current: ON)
0-Load options file
a-Load options from saved Burp request
b-Save options file
x-Back to main menu
Select an option: x
[3;J
====================================================
 _   _       _____  _____ _     ___  ___            
| \ | |     /  ___||  _  | |    |  \/  |            
|  \| | ___ \ `--. | | | | |    | .  . | __ _ _ __  
| . ` |/ _ \ `--. \| | | | |    | |\/| |/ _` | '_ \ 
| |\  | (_) /\__/ /\ \/' / |____| |  | | (_| | |_) |
\_| \_/\___/\____/  \_/\_\_____/\_|  |_/\__,_| .__/
====================================================
NoSQLMap-v0.5
nosqlmap@gmail.com


1-Set options
2-NoSQL DB Access Attacks
3-NoSQL Web App attacks
4-Scan for Anonymous MongoDB Access
5-Change Platform (Current: MongoDB)
x-Exit
Select an option: 3
Web App Attacks (GET)
===============
Checking to see if site at xx.xx.xx.xxx:443/cgi-bin/mongo/2.2.3/dbparse.py is up...
Looks like the server didn't respond.  Check your options.
Press enter to continue...
[3;J


====================================================
 _   _       _____  _____ _     ___  ___            
| \ | |     /  ___||  _  | |    |  \/  |            
|  \| | ___ \ `--. | | | | |    | .  . | __ _ _ __  
| . ` |/ _ \ `--. \| | | | |    | |\/| |/ _` | '_ \ 
| |\  | (_) /\__/ /\ \/' / |____| |  | | (_| | |_) |
\_| \_/\___/\____/  \_/\_\_____/\_|  |_/\__,_| .__/
====================================================
NoSQLMap-v0.5
nosqlmap@gmail.com


1-Set options
2-NoSQL DB Access Attacks
3-NoSQL Web App attacks
4-Scan for Anonymous MongoDB Access
5-Change Platform (Current: MongoDB)
x-Exit
Select an option: x
root@kali:~/NoSQLMap-0.5#
root@kali:~/NoSQLMap-0.5#
root@kali:~/NoSQLMap-0.5#
root@kali:~/NoSQLMap-0.5# curl -I -k https://xx.xx.xx.xxx/cgi-bin/mongo/2.2.3/dbparse.py
HTTP/1.1 200 OK
Date: Mon, 11 Jan 2016 06:17:12 GMT
Server: Apache/xx.xx.xx (xx)
Vary: Accept-Encoding
Content-Type: text/html

root@kali:~/NoSQLMap-0.5#
```

**Comment by g0tmi1k** [comment] 2016-01-11 15:20
**Another issue**.

Trying to re-run it, causes another issue

```
====================================================
 _   _       _____  _____ _     ___  ___            
| \ | |     /  ___||  _  | |    |  \/  |            
|  \| | ___ \ `--. | | | | |    | .  . | __ _ _ __  
| . ` |/ _ \ `--. \| | | | |    | |\/| |/ _` | '_ \ 
| |\  | (_) /\__/ /\ \/' / |____| |  | | (_| | |_) |
\_| \_/\___/\____/  \_/\_\_____/\_|  |_/\__,_| .__/
====================================================
NoSQLMap-v0.5
nosqlmap@gmail.com


1-Set options
2-NoSQL DB Access Attacks
3-NoSQL Web App attacks
4-Scan for Anonymous MongoDB Access
5-Change Platform (Current: MongoDB)
x-Exit
Select an option: 3
Web App Attacks (GET)
===============
Checking to see if site at 10.11.1.238:443/cgi-bin/mongo/2.2.3/dbparse.py is up...
Looks like the server didn't respond.  Check your options.
Press enter to continue...
[3;J


====================================================
 _   _       _____  _____ _     ___  ___            
| \ | |     /  ___||  _  | |    |  \/  |            
|  \| | ___ \ `--. | | | | |    | .  . | __ _ _ __  
| . ` |/ _ \ `--. \| | | | |    | |\/| |/ _` | '_ \ 
| |\  | (_) /\__/ /\ \/' / |____| |  | | (_| | |_) |
\_| \_/\___/\____/  \_/\_\_____/\_|  |_/\__,_| .__/
====================================================
NoSQLMap-v0.5
nosqlmap@gmail.com


1-Set options
2-NoSQL DB Access Attacks
3-NoSQL Web App attacks
4-Scan for Anonymous MongoDB Access
5-Change Platform (Current: MongoDB)
x-Exit
Select an option: 1
Traceback (most recent call last):
  File "nosqlmap.py", line 1752, in <module>
    main()
  File "nosqlmap.py", line 60, in main
    mainMenu()
  File "nosqlmap.py", line 93, in mainMenu
    options()
  File "nosqlmap.py", line 199, in options
    while optSelect:
UnboundLocalError: local variable 'optSelect' referenced before assignment
root@kali:~/NoSQLMap-0.5# 
```

- - -

I've enabled verbose mode, however I'm not seeing what status code is being returned back.

**Comment by tcstool** [comment] 2016-01-11 15:28
Can you disable the SSL and test it? Most likely an untrusted cert is
throwing an exception.

**Comment by g0tmi1k** [comment] 2016-01-11 15:31
Yes, it is a self sign cert.
Disabling SSL at this stage will be a pain...

**Comment by tcstool** [comment] 2016-01-11 15:32
Ok.  Let me look at it tonight and see what I can do.

**Comment by tcstool** [comment] 2016-01-12 00:41
I can't replicate the crash when you try to set the options again.  Can you give me more info? Did you load the options in from a file or something like that?

**Comment by tcstool** [comment] 2016-01-12 01:01
I can't replicate the SSL certificate issue either. Is it possible you're running on a machine where Python was compiled without SSL support, or your way you installed URLLib2 was compiled without SSL support?

**Comment by tcstool** [comment] 2016-01-12 01:17
Traced back through your output and found the crash issue.  It's an edge case that can occur with a combination of loading an options file and retrying to set the options after a load.  I've got a fix I'm testing now.  I'm still not sure about your other problem.  If you provide me a way to get you a patched version that will give a more detailed diagnostic, I'll send it over.

**Comment by g0tmi1k** [comment] 2016-01-12 08:10
REF: Crash - see the output before.
Same setup, same deal. 
Re-ran the first bit - it was unable to find the server. Upon re-running the exact same options & commands it would crash a second time around.
So yes, its loading from a file. Output of the file contents is in the first section.

REF Python options
Its a stock Kali 2 x64 ISO (full). Not even upgraded (via `apt-get dist-upgrade`).

REF Fix
I can DM you an email address on twitter. Else you can upload something to pastebin or zip it up and share it via a online file hosting (e.g. http://expirebox.com/).
Else why not commit it so it be the verbose option in the program? Or add a debug option?

**Comment by g0tmi1k** [comment] 2016-01-12 09:00
I can confirm that commit 295cc748378f38cc9fccb004e1b1063a1fe166c1 fixes the menu bug!

Here is a video showing the SSL issue/problem: http://expirebox.com/download/a8a9bb65c5fc11ac710668e666fd58e1.html (Will run out in 48 hours)
NoSQLMap was already installed before hand (which is why `python setup.py install` was so darn quick!).
I am aware that SQLMap would of never worked - however, just doing it to show that it was able to access the same target.

**Comment by tcstool** [comment] 2016-01-12 15:47
I have successfully replicated the problem.  The issue is a change between Python 2.7.3 to not validate certificates by default and 2.7.9 which always validates certificates by default.  I am going to rewrite all the URL reads to detect the version of Python in use and, if greater than 2.7.3, add a default SSL context handler to bypass certificate validation.

**Comment by tcstool** [comment] 2016-01-12 22:58
Updated on this issue:  I've gone through the code and have started working on a fix. However, it's going to require a significant number of changes to be implemented, so it may take a few days to get everything changed and tested.  I will advise when complete.  Thanks for the heads up on this one.

**Comment by zeroparity** [comment] 2016-02-16 18:49
https://github.com/abeloin/SickRage/commit/21fcea2c3155f57dba5c64a55f1f8fee02804256

This fix worked for me.

**Comment by tcstool** [comment] 2016-02-17 20:17
Yep, that's exactly what I'm trying to implement into a centralized web
request handler.  I just haven't had time to finish it, been busy with a
SANS onDemand course that is ruling my life right now.  Hopefully soon.
Feel free to put some code together if you want :-D

**Comment by tcstool** [comment] 2017-08-22 21:34
This was fixed in the last push by creating an unverified SSL context in the URL handler (see lines 27-29 of nsmweb.py).  I failed to close the issue.

**Closed by tcstool** 2017-08-22 21:34 UTC
Labels: bug

**Comment by g0tmi1k** [comment] 2017-08-23 07:53
https://github.com/codingo/NoSQLMap/commit/54b36cf9f1fa817dd88cc8e97cd822241c0a5867
